---
- hosts: ethfullnodes
  become: true

  # These are the tasks to run before applying updates:
  pre_tasks:
  - name: Stop nethermind service
    systemd:
      name: nethermind
      state: stopped
    ignore_errors: no

  - name: Stop nimbus_beacon_node service
    systemd:
      name: nimbus_beacon_node
      state: stopped
    ignore_errors: no

  roles:
  - nimbus
  - nethermind

